services:
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=7d"

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  redis-exporter-master:
    image: oliver006/redis_exporter:v1.61.0
    container_name: redis-exporter-master
    command:
      - "--redis.addr=${REDIS_MASTER_ADDR:-redis://192.168.139.86:6379}"
    ports:
      - "9121:9121"

  redis-exporter-replica:
    image: oliver006/redis_exporter:v1.61.0
    container_name: redis-exporter-replica
    command:
      - "--redis.addr=${REDIS_REPLICA_ADDR:-redis://192.168.139.86:6380}"
      - "--web.listen-address=:9122"
    ports:
      - "9122:9122"

volumes:
  prometheus_data:
  grafana_data:
