x-redis-common: &redis-common
  image: redis:7-alpine
  command: >
    redis-server
    --cluster-enabled yes
    --cluster-config-file nodes.conf
    --cluster-node-timeout 5000
    --appendonly yes
    --appendfsync everysec
    --maxmemory 256mb
    --maxmemory-policy allkeys-lru

services:
  # VM1 — Мастер Shard 1 + Реплика Shard 2
  shard1-master:
    <<: *redis-common
    ports:
      - "7001:6379"
    volumes:
      - shard1-master-data:/data

  shard2-replica:
    <<: *redis-common
    ports:
      - "7021:6379"
    volumes:
      - shard2-replica-data:/data
    depends_on:
      - shard2-master

  # VM2 — Мастер Shard 2 + Реплика Shard 3
  shard2-master:
    <<: *redis-common
    ports:
      - "7002:6379"
    volumes:
      - shard2-master-data:/data

  shard3-replica:
    <<: *redis-common
    ports:
      - "7031:6379"
    volumes:
      - shard3-replica-data:/data
    depends_on:
      - shard3-master

  # VM3 — Мастер Shard 3 + Реплика Shard 1
  shard3-master:
    <<: *redis-common
    ports:
      - "7003:6379"
    volumes:
      - shard3-master-data:/data

  shard1-replica:
    <<: *redis-common
    ports:
      - "7011:6379"
    volumes:
      - shard1-replica-data:/data
    depends_on:
      - shard1-master

volumes:
  shard1-master-data:
  shard1-replica-data:
  shard2-master-data:
  shard2-replica-data:
  shard3-master-data:
  shard3-replica-data:
